// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 Parth Sinha

// Phase 4, issue #54: the reproducibility claim, as a test rather than an
// assertion.
//
// vphilox promises that a given (key, counter) yields the same bytes on every
// architecture, compiler and release. Until now the only thing enforcing that
// was tests/test_reference_vectors.cpp, which checks three published KAT
// counters through the scalar kernel. That leaves the parts most likely to
// diverge untested across architectures: the SIMD tail paths, the engine's
// refill buffer, the counter carry chain, and the float conversion.
//
// So: fold a long stream into a digest and check it against a constant checked
// in below. Every CI leg -- x86-64 Linux, macOS arm64, Windows MSVC -- then
// enforces the invariant on every commit, and the same binary run on real
// aarch64 confirms it there.
//
// If one of these fails, the generated stream has changed. Per the project's
// invariant that is a wrong change, not a stale test: a different stream is a
// different generator. Do not update the constants to make the test pass
// unless you can say precisely why the old digest was itself incorrect.
//
// The digest is FNV-1a over explicitly little-endian bytes. Not cryptographic
// -- it does not need to be, since it defends against accidental change rather
// than a forger -- but it is dependency-free and its own definition is fixed
// here, so it cannot drift with a library version.

#include <gtest/gtest.h>

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <vector>

#include "vphilox/vphilox.hpp"

namespace {

constexpr std::uint64_t kFnvOffset = 0xcbf29ce484222325ull;
constexpr std::uint64_t kFnvPrime  = 0x100000001b3ull;

/// Absorb one word as four little-endian bytes. Spelling the byte order out
/// is the point: hashing the object representation would bake the host's
/// endianness into the constant and make this test pass everywhere while
/// proving nothing.
constexpr void absorb(std::uint64_t& h, vphilox::u32 v) noexcept {
    for (int i = 0; i < 4; ++i) {
        h ^= static_cast<std::uint8_t>((v >> (8 * i)) & 0xFFu);
        h *= kFnvPrime;
    }
}

[[nodiscard]] std::uint64_t digest(const std::vector<vphilox::u32>& words) noexcept {
    std::uint64_t h = kFnvOffset;
    for (const auto w : words) absorb(h, w);
    return h;
}

/// Bit pattern of a float, absorbed as a word. Catches any difference in the
/// mantissa-injection path, which is where a compiler is most likely to take
/// a liberty.
[[nodiscard]] std::uint64_t digest_floats(const std::vector<float>& values) noexcept {
    std::uint64_t h = kFnvOffset;
    for (const auto f : values) {
        vphilox::u32 bits{};
        std::memcpy(&bits, &f, sizeof(bits));
        absorb(h, bits);
    }
    return h;
}

// The fixtures. Block counts are deliberately not multiples of any SIMD width,
// so every backend runs its tail path on the way to the digest.
constexpr vphilox::u64 kBlocks = 8191;
constexpr std::size_t kWords   = static_cast<std::size_t>(kBlocks) * vphilox::block_words;

const vphilox::key2 kKey{{0x243F6A88u, 0x85A308D3u}};  // digits of pi, as the KATs use

/// A counter positioned so the run carries through every word boundary of the
/// 128-bit counter, which is the arithmetic most likely to differ if someone
/// reimplements it.
vphilox::counter4 carry_start() noexcept {
    return vphilox::counter4{{0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0x00000000u}};
}

// ---------------------------------------------------------------------------
// Expected digests. Generated by this test on x86-64 and confirmed byte for
// byte against the scalar kernel, which is the reference implementation.
// ---------------------------------------------------------------------------
constexpr std::uint64_t kDigestFromZero  = 0xA7434CA5A44405DFull;
constexpr std::uint64_t kDigestFromCarry = 0xA105B83D1B7423C0ull;
constexpr std::uint64_t kDigestFloats    = 0x463401A909F236B6ull;

[[nodiscard]] std::vector<vphilox::u32> kernel_stream(vphilox::counter4 start) {
    std::vector<vphilox::u32> out(kWords);
    vphilox::detail::resolve_dispatch<vphilox::default_rounds>().fn(start, kKey, out.data(),
                                                                    kBlocks);
    return out;
}

[[nodiscard]] std::vector<vphilox::u32> scalar_stream(vphilox::counter4 start) {
    std::vector<vphilox::u32> out(kWords);
    vphilox::detail::kernel_scalar::generate<vphilox::default_rounds>(start, kKey, out.data(),
                                                                      kBlocks);
    return out;
}

TEST(CrossPlatformParity, KernelStreamFromZeroMatchesDigest) {
    EXPECT_EQ(digest(kernel_stream(vphilox::counter4{})), kDigestFromZero)
        << "the generated stream has changed; see the note at the top of this file";
}

TEST(CrossPlatformParity, KernelStreamAcrossCarryMatchesDigest) {
    EXPECT_EQ(digest(kernel_stream(carry_start())), kDigestFromCarry);
}

/// The active backend must agree with the reference implementation, not merely
/// with a previously recorded value. On a scalar-only build these are the same
/// call; on AVX2 this is what makes the digest meaningful.
TEST(CrossPlatformParity, ActiveBackendMatchesScalarReference) {
    EXPECT_EQ(kernel_stream(vphilox::counter4{}), scalar_stream(vphilox::counter4{}));
    EXPECT_EQ(kernel_stream(carry_start()), scalar_stream(carry_start()));
}

/// The engine reaches the same bytes through the refill buffer, so the buffer
/// is covered by the same constant rather than needing one of its own.
TEST(CrossPlatformParity, EngineMatchesKernelDigest) {
    vphilox::engine g{kKey, vphilox::counter4{}};
    std::vector<vphilox::u32> out(kWords);
    for (auto& w : out) w = g();
    EXPECT_EQ(digest(out), kDigestFromZero);
}

TEST(CrossPlatformParity, BulkPathMatchesKernelDigest) {
    vphilox::engine g{kKey, vphilox::counter4{}};
    std::vector<vphilox::u32> out(kWords);
    g.generate_n(out.data(), out.size());
    EXPECT_EQ(digest(out), kDigestFromZero);
}

/// Chunking must not change the stream. Sizes straddle every plausible SIMD
/// width so a backend that mishandles a partial vector shows up here.
TEST(CrossPlatformParity, ChunkedGenerationMatchesDigest) {
    for (const std::size_t chunk : {std::size_t{1}, std::size_t{3}, std::size_t{7}, std::size_t{8},
                                    std::size_t{31}, std::size_t{32}}) {
        vphilox::engine g{kKey, vphilox::counter4{}};
        std::vector<vphilox::u32> out(kWords);
        for (std::size_t i = 0; i < kWords; i += chunk) {
            g.generate_n(out.data() + i, std::min(chunk, kWords - i));
        }
        EXPECT_EQ(digest(out), kDigestFromZero) << "chunk size " << chunk;
    }
}

/// IEEE-754 mantissa injection has to be bit-stable too, or a reproducible
/// integer stream still yields irreproducible simulations.
TEST(CrossPlatformParity, FloatConversionMatchesDigest) {
    vphilox::engine g{kKey, vphilox::counter4{}};
    std::vector<float> out(kWords);
    g.generate_n(out.data(), out.size());
    EXPECT_EQ(digest_floats(out), kDigestFloats);
}

/// The digest itself must be stable, or a failure above is ambiguous between
/// "the stream changed" and "the hash changed".
TEST(CrossPlatformParity, DigestFunctionIsItselfPinned) {
    std::uint64_t h = kFnvOffset;
    absorb(h, 0x00000000u);
    absorb(h, 0xFFFFFFFFu);
    absorb(h, 0x01234567u);
    EXPECT_EQ(h, 0x51F321EF608150F9ull);
}

}  // namespace
